# -*- coding: utf-8 -*-
"""spp_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gA2mwM_dVAN-pGTsI4to4Xeg7IaxJVJm
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from datetime import datetime

# Load data, skipping the first 4 rows and using the 5th row (index 4) as header
data = pd.read_csv('/content/drive/MyDrive/spp_data.csv', skiprows=4, header=0)

# Rename columns for easier access if needed (based on the actual header row)
# Assuming the headers are 'Nama Siswa', 'Kelas', 'Tanggal Bayar', 'Jumlah Bayar'
data.columns = ['Nama Siswa', 'Kelas', 'Tanggal Bayar', 'Jumlah Bayar']

# Convert 'Tanggal Bayar' to datetime objects
data['Tanggal Bayar'] = pd.to_datetime(data['Tanggal Bayar'], format='%d/%m/%Y', errors='coerce')

# Convert 'Jumlah Bayar' to numeric
data['Jumlah Bayar'] = data['Jumlah Bayar'].astype(str).str.replace('Rp', '', regex=False).str.replace('.', '', regex=False)
data['Jumlah Bayar'] = pd.to_numeric(data['Jumlah Bayar'], errors='coerce').fillna(0)

print(data.head())
print("\nData types after conversion:")
print(data.dtypes)

# Define constants (contoh: tanggal rekap hari ini, jumlah spp per bulan)
TANGGAL_REKAP = datetime(2025, 7, 15) # Ganti dengan tanggal rekap yang sebenarnya
JUMLAH_SPP = 1000000 # Ganti dengan jumlah spp yang sebenarnya

# Tambahkan kolom bantu: bulan & tahun pembayaran
# Pastikan kolom 'Tanggal Bayar' sudah dalam format datetime
data["Bulan"] = data["Tanggal Bayar"].dt.month
data["Tahun"] = data["Tanggal Bayar"].dt.year

# Ambil bulan dan tahun dari tanggal rekap
bulan_ini = TANGGAL_REKAP.month
tahun_ini = TANGGAL_REKAP.year

# ===================== #
# FILTER PEMBAYARAN BULAN INI SEBELUM TGL 10
# Gunakan 'data' bukan 'df'
# ===================== #
sudah_bayar = data[
    (data["Tanggal Bayar"].dt.month == bulan_ini) &
    (data["Tanggal Bayar"].dt.year == tahun_ini) &
    (data["Tanggal Bayar"] <= TANGGAL_REKAP)
].copy() # Gunakan .copy() untuk menghindari SettingWithCopyWarning

# Ambil daftar unik siswa
# Gunakan 'data' bukan 'df'
semua_siswa = data[["Nama Siswa", "Kelas"]].drop_duplicates().copy() # Gunakan .copy()

# Cek siapa yang bayar
semua_siswa["Status"] = semua_siswa["Nama Siswa"].isin(sudah_bayar["Nama Siswa"])
semua_siswa["Status"] = semua_siswa["Status"].map({True: "Lunas", False: "Belum Lunas"})

# Tambahkan total yang dibayar bulan ini
total_bayar = sudah_bayar.groupby("Nama Siswa")["Jumlah Bayar"].sum().reset_index()
total_bayar.columns = ["Nama Siswa", "Total Bayar Bulan Ini"]

rekap = pd.merge(semua_siswa, total_bayar, on="Nama Siswa", how="left")
rekap["Total Bayar Bulan Ini"] = rekap["Total Bayar Bulan Ini"].fillna(0)
rekap["Kekurangan"] = JUMLAH_SPP - rekap["Total Bayar Bulan Ini"]
rekap["Kekurangan"] = rekap["Kekurangan"].clip(lower=0)

# ===================== #
# OUTPUT
# ===================== #
rekap = rekap.sort_values(by=["Kelas", "Nama Siswa"])
print(rekap)

# Simpan ke file Excel/CSV jika mau
rekap.to_csv("rekap_spp_bulan_ini.csv", index=False)